serverstatus:
  name: Lobby-1
  group: "Lobby"
  website: "www.example.com"
  first-message: "§6Welcome to Leafed"

tablist:
  server-title: "§7§lLEAFED.CC"
  message: "§61.30 update soon."

elytrafly:
  vdouble: 2.344
  sendspeed: false
  sendmessage: true
  tp: true

database:
  host: "10.0.0.114"
  username: "minecraft"
  password: "8Teh1XO4[.C/*NCl"
  data: "minecraft"